package exception3;

public class Exception03_353p {

	public static void main(String[] args) {
		
		// 다중 catch는 블럭 내부에서 [여러유형의 예외가 발생할 수 있을 때]
		// 각각의 예외유형을 [다르게 처리할 때] 사용한다.
		// 이때 [catch 구문을 여러번] 사용할 수 있다.
		
		int[] number = {1,2,3,4,5,0};
		
		try {
			for(int i=0; i<7; i++) { //ArrayOutofBoundException
				System.out.println(number[i]);
			}
			System.out.println(number[4]/number[5]); //AritimeticException
		}
		catch(Exception e) {
		    
		}
	}
}


